import { APIBooking } from "~/entities/booking/types";
import type { APITravel } from "~/entities/travel/types";
import { APICustomer } from "~/entities/customer/types";

export const getMockedTravelsData = (): APITravel[] => [
  {
    id: "1",
    name: "Iceland: waterfalls and volcanoes",
    thumbnail_url:
      "https://images.unsplash.com/photo-1621959721891-d297dfd9d6ee?q=80&w=2076&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The land of fire and ice",
    departure_date: "2022-01-01",
    return_date: "2022-01-07",
    price_per_person: "1380",
  },
  {
    id: "2",
    name: "Japan: culture and tradition",
    thumbnail_url:
      "https://images.unsplash.com/photo-1504109586057-7a2ae83d1338?q=80&w=2066&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The land of the rising sun",
    departure_date: "2022-02-01",
    return_date: "2022-02-12",
    price_per_person: "2110",
  },
  {
    id: "3",
    name: "Brazil: beaches and carnival",
    thumbnail_url:
      "https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The land of the samba",
    departure_date: "2022-03-01",
    return_date: "2022-03-10",
    price_per_person: "950",
  },
  {
    id: "4",
    name: "Australia: kangaroos and koalas",
    thumbnail_url:
      "https://images.unsplash.com/photo-1624138784614-87fd1b6528f8?q=80&w=2066&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The land of the kangaroo",
    departure_date: "2022-04-01",
    return_date: "2022-04-16",
    price_per_person: "1800",
  },
  {
    id: "5",
    name: "France: croissants and wine",
    thumbnail_url:
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=2073&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The land of the croissant",
    departure_date: "2022-05-01",
    return_date: "2022-05-08",
    price_per_person: "1200",
  },
  {
    id: "6",
    name: "Germany: beer and sausages",
    thumbnail_url:
      "https://images.unsplash.com/photo-1559564484-e48b3e040ff4?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The land of the beer",
    departure_date: "2022-06-01",
    return_date: "2022-06-10",
    price_per_person: "1100",
  },
  {
    id: "7",
    name: "Italy: pizza and pasta",
    thumbnail_url:
      "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The land of the pizza",
    departure_date: "2022-07-01",
    return_date: "2022-07-11",
    price_per_person: "1300",
  },
  {
    id: "8",
    name: "Spain: paella and flamenco",
    thumbnail_url:
      "https://images.unsplash.com/photo-1511527661048-7fe73d85e9a4?q=80&w=1965&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The land of the paella",
    departure_date: "2022-08-01",
    return_date: "2022-08-07",
    price_per_person: "1000",
  },
  {
    id: "9",
    name: "Portugal: fado and pastéis de nata",
    thumbnail_url:
      "https://images.unsplash.com/photo-1529699074188-d1fb8244c4ca?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The land of the fado",
    departure_date: "2022-09-01",
    return_date: "2022-09-10",
    price_per_person: "950",
  },
  {
    id: "10",
    name: "Argentina: tango and asado",
    thumbnail_url:
      "https://images.unsplash.com/photo-1612900538226-0e2140aa02f6?q=80&w=1965&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The land of the tango",
    departure_date: "2022-10-01",
    return_date: "2022-10-14",
    price_per_person: "1200",
  },
  {
    id: "11",
    name: "Greece: Santorini Sunsets",
    thumbnail_url:
      "https://images.unsplash.com/photo-1678266561093-324802646fb2?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Experience the stunning sunsets and crystal-clear waters.",
    departure_date: "2022-09-15",
    return_date: "2022-09-25",
    price_per_person: "1500",
  },
  {
    id: "12",
    name: "Switzerland: Alps and Zurich",
    thumbnail_url:
      "https://images.unsplash.com/photo-1517490560101-4ffe479ef5c3?q=80&w=1965&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Ski in the Swiss Alps and explore the charming city of Zurich.",
    departure_date: "2023-12-15",
    return_date: "2023-12-25",
    price_per_person: "2400",
  },
  {
    id: "13",
    name: "Iceland: Northern Lights",
    thumbnail_url:
      "https://images.unsplash.com/photo-1488703480497-dfcccd4894d1?q=80&w=2069&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Witness the spectacular Northern Lights and explore Iceland's unique landscapes.",
    departure_date: "2023-12-01",
    return_date: "2023-12-10",
    price_per_person: "2200",
  },
  {
    id: "14",
    name: "Australia: Surf and Outback",
    thumbnail_url:
      "https://images.unsplash.com/photo-1503022932596-500eb8cca2d8?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Experience the vibrant city life and rugged outback adventures.",
    departure_date: "2023-02-10",
    return_date: "2023-02-25",
    price_per_person: "2000",
  },
  {
    id: "15",
    name: "Peru: Machu Picchu Expedition",
    thumbnail_url:
      "https://images.unsplash.com/photo-1532996152552-eaffc4edfc1a?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Hike the Inca Trail and explore the ancient ruins of Machu Picchu.",
    departure_date: "2023-05-01",
    return_date: "2023-05-14",
    price_per_person: "1700",
  },
  {
    id: "16",
    name: "Morocco: Desert and Medina",
    thumbnail_url:
      "https://images.unsplash.com/photo-1451245420434-8f0ce5b89693?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Discover the vibrant markets and stunning desert landscapes.",
    departure_date: "2023-06-10",
    return_date: "2023-06-20",
    price_per_person: "1600",
  },
  {
    id: "17",
    name: "Canada: Rockies and Vancouver",
    thumbnail_url:
      "https://images.unsplash.com/photo-1536637706725-c96e8837df7d?q=80&w=2000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Explore the breathtaking landscapes of the Rocky Mountains and the vibrant city of Vancouver.",
    departure_date: "2023-07-05",
    return_date: "2023-07-15",
    price_per_person: "1900",
  },
  {
    id: "18",
    name: "Thailand: Bangkok and Beaches",
    thumbnail_url:
      "https://images.unsplash.com/photo-1494949360228-4e9bde560065?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Immerse yourself in the vibrant culture and beautiful beaches of Thailand.",
    departure_date: "2023-01-10",
    return_date: "2023-01-25",
    price_per_person: "1300",
  },
  {
    id: "19",
    name: "Egypt: Pyramids and Nile Cruise",
    thumbnail_url:
      "https://images.unsplash.com/photo-1544815521-80841127c00f?q=80&w=2109&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Explore the ancient pyramids and cruise down the Nile River.",
    departure_date: "2023-11-10",
    return_date: "2023-11-20",
    price_per_person: "1800",
  },
  {
    id: "20",
    name: "New Zealand: Adventure and Nature",
    thumbnail_url:
      "https://images.unsplash.com/photo-1531804159968-24716780d214?q=80&w=1976&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Experience the stunning natural landscapes and adventurous activities in New Zealand.",
    departure_date: "2023-09-01",
    return_date: "2023-09-15",
    price_per_person: "2100",
  },
];

export const getMockedCustomersData = (): APICustomer[] => [
  {
    id: "1",
    first_name: "John",
    last_name: "Doe",
    email: "john.doe@mail.com",
    phone_number: "123456789",
    age: 30,
    gender: "man",
    profile_picture: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: "2",
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@mail.com",
    phone_number: "987654321",
    age: 28,
    gender: "woman",
    profile_picture: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: "3",
    first_name: "Michael",
    last_name: "Johnson",
    email: "michael.johnson@mail.com",
    phone_number: "234567891",
    age: 35,
    gender: "man",
    profile_picture: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: "4",
    first_name: "Emily",
    last_name: "Davis",
    email: "emily.davis@mail.com",
    phone_number: "345678912",
    age: 32,
    gender: "woman",
    profile_picture: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: "5",
    first_name: "David",
    last_name: "Brown",
    email: "david.brown@mail.com",
    phone_number: "456789123",
    age: 29,
    gender: "man",
    profile_picture: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: "6",
    first_name: "Sarah",
    last_name: "Wilson",
    email: "sarah.wilson@mail.com",
    phone_number: "567891234",
    age: 27,
    gender: "woman",
    profile_picture: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: "7",
    first_name: "Chris",
    last_name: "Martinez",
    email: "chris.martinez@mail.com",
    phone_number: "678912345",
    age: 33,
    gender: "man",
    profile_picture: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: "8",
    first_name: "Laura",
    last_name: "Garcia",
    email: "laura.garcia@mail.com",
    phone_number: "789123456",
    age: 31,
    gender: "woman",
    profile_picture: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: "9",
    first_name: "James",
    last_name: "Rodriguez",
    email: "james.rodriguez@mail.com",
    phone_number: "891234567",
    age: 36,
    gender: "man",
    profile_picture: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: "10",
    first_name: "Olivia",
    last_name: "Hernandez",
    email: "olivia.hernandez@mail.com",
    phone_number: "912345678",
    age: 26,
    gender: "woman",
    profile_picture: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: "11",
    first_name: "Liam",
    last_name: "Wilson",
    email: "liam.wilson@mail.com",
    phone_number: "913456789",
    age: 28,
    gender: "man",
    profile_picture: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: "12",
    first_name: "Emma",
    last_name: "Johnson",
    email: "emma.johnson@mail.com",
    phone_number: "914567890",
    age: 22,
    gender: "woman",
    profile_picture: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: "13",
    first_name: "Noah",
    last_name: "Brown",
    email: "noah.brown@mail.com",
    phone_number: "915678901",
    age: 30,
    gender: "man",
    profile_picture: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: "14",
    first_name: "Sophia",
    last_name: "Jones",
    email: "sophia.jones@mail.com",
    phone_number: "916789012",
    age: 24,
    gender: "woman",
    profile_picture: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: "15",
    first_name: "James",
    last_name: "Garcia",
    email: "james.garcia@mail.com",
    phone_number: "917890123",
    age: 27,
    gender: "man",
    profile_picture: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: "16",
    first_name: "Isabella",
    last_name: "Martinez",
    email: "isabella.martinez@mail.com",
    phone_number: "918901234",
    age: 23,
    gender: "woman",
    profile_picture: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: "17",
    first_name: "Benjamin",
    last_name: "Rodriguez",
    email: "benjamin.rodriguez@mail.com",
    phone_number: "919012345",
    age: 29,
    gender: "man",
    profile_picture: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    id: "18",
    first_name: "Mia",
    last_name: "Miller",
    email: "mia.miller@mail.com",
    phone_number: "920123456",
    age: 25,
    gender: "woman",
    profile_picture: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: "19",
    first_name: "Elijah",
    last_name: "Davis",
    email: "elijah.davis@mail.com",
    phone_number: "921234567",
    age: 31,
    gender: "man",
    profile_picture: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    id: "20",
    first_name: "Ava",
    last_name: "Martinez",
    email: "ava.martinez@mail.com",
    phone_number: "922345678",
    age: 26,
    gender: "woman",
    profile_picture: "https://randomuser.me/api/portraits/women/20.jpg",
  },
];

export const getMockedBookingsData = (): APIBooking[] => {
  const mockedTravels = getMockedTravelsData();
  const mockedCustomers = getMockedCustomersData();

  return [
    {
      id: "1",
      travel: mockedTravels.find((travel) => travel.id === "18")!,
      customer: mockedCustomers.find((customer) => customer.id === "1")!,
      payment_method: "Credit transfer",
      internal_notes: "No allergies",
    },
    {
      id: "2",
      travel: mockedTravels.find((travel) => travel.id === "2")!,
      customer: mockedCustomers.find((customer) => customer.id === "8")!,
      payment_method: "Paypal",
    },
    {
      id: "3",
      travel: mockedTravels.find((travel) => travel.id === "1")!,
      customer: mockedCustomers.find((customer) => customer.id === "2")!,
      payment_method: "Revolut",
      internal_notes: "Vegetarian",
    },
    {
      id: "4",
      travel: mockedTravels.find((travel) => travel.id === "7")!,
      customer: mockedCustomers.find((customer) => customer.id === "4")!,
      payment_method: "Credit transfer",
    },
    {
      id: "5",
      travel: mockedTravels.find((travel) => travel.id === "5")!,
      customer: mockedCustomers.find((customer) => customer.id === "9")!,
      payment_method: "Paypal",
    },
    {
      id: "6",
      travel: mockedTravels.find((travel) => travel.id === "2")!,
      customer: mockedCustomers.find((customer) => customer.id === "10")!,
      payment_method: "Credit transfer",
    },
    {
      id: "7",
      travel: mockedTravels.find((travel) => travel.id === "7")!,
      customer: mockedCustomers.find((customer) => customer.id === "11")!,
      payment_method: "Paypal",
    },
    {
      id: "8",
      travel: mockedTravels.find((travel) => travel.id === "10")!,
      customer: mockedCustomers.find((customer) => customer.id === "12")!,
      payment_method: "Revolut",
    },
    {
      id: "9",
      travel: mockedTravels.find((travel) => travel.id === "1")!,
      customer: mockedCustomers.find((customer) => customer.id === "13")!,
      payment_method: "Revolut",
    },
    {
      id: "10",
      travel: mockedTravels.find((travel) => travel.id === "4")!,
      customer: mockedCustomers.find((customer) => customer.id === "14")!,
      payment_method: "Paypal",
    },
    {
      id: "11",
      travel: mockedTravels.find((travel) => travel.id === "12")!,
      customer: mockedCustomers.find((customer) => customer.id === "15")!,
      payment_method: "Revolut",
    },
    {
      id: "12",
      travel: mockedTravels.find((travel) => travel.id === "14")!,
      customer: mockedCustomers.find((customer) => customer.id === "16")!,
      payment_method: "Credit transfer",
    },
    {
      id: "13",
      travel: mockedTravels.find((travel) => travel.id === "15")!,
      customer: mockedCustomers.find((customer) => customer.id === "17")!,
      payment_method: "Credit transfer",
    },
    {
      id: "14",
      travel: mockedTravels.find((travel) => travel.id === "10")!,
      customer: mockedCustomers.find((customer) => customer.id === "18")!,
      payment_method: "Revolut",
    },
    {
      id: "15",
      travel: mockedTravels.find((travel) => travel.id === "20")!,
      customer: mockedCustomers.find((customer) => customer.id === "19")!,
      payment_method: "Credit transfer",
    },
  ];
};
